[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/accounts"
  to = "/.netlify/functions/accounts"
  status = 200

[[redirects]]
  from = "/api/claim"
  to = "/.netlify/functions/claim"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
